import { useCallback, useEffect, useState } from 'react';
import { Plus, RefreshCw, TicketPercent } from 'lucide-react';
import { createAdminCoupon, fetchAdminCoupons, updateAdminCoupon } from '../../lib/rewardsApi';
import EmptyState from '../../components/shared/EmptyState';
import './CouponManagement.css';

const EMPTY = { code: '', title: '', description: '', points_cost: 100, discount_type: 'fixed', discount_value: 50, starts_at: '', expires_at: '', stock: '', status: 'draft' };
const STATUS_LABEL = { draft: '草稿', active: '上架中', paused: '已暫停', expired: '已過期' };

function toApiDate(value) { return value ? new Date(value).toISOString() : null; }

export default function CouponManagement() {
  const [coupons, setCoupons] = useState([]); const [form, setForm] = useState(EMPTY); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setCoupons(await fetchAdminCoupons()); } catch (err) { setError(err.message || '優惠券資料載入失敗。'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  function change(key, value) { setForm(current => ({ ...current, [key]: value })); }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { await createAdminCoupon({ ...form, points_cost: Number(form.points_cost), discount_value: Number(form.discount_value), stock: form.stock ? Number(form.stock) : null, starts_at: toApiDate(form.starts_at), expires_at: toApiDate(form.expires_at) }); setForm(EMPTY); setMessage('優惠券已建立。'); await load(); } catch (err) { setError(err.message || '建立優惠券失敗。'); } finally { setSaving(false); } }
  async function toggle(coupon) { const status = coupon.status === 'active' ? 'paused' : 'active'; try { await updateAdminCoupon(coupon.id, { status }); setMessage(`已${status === 'active' ? '啟用' : '暫停'}「${coupon.title}」。`); await load(); } catch (err) { setError(err.message || '更新優惠券失敗。'); } }
  return <div className="coupon-management"><header className="page-heading"><div><p className="eyebrow">REWARD OPERATIONS</p><h1>優惠券管理</h1><p>建立點數兌換券、設定折扣、有效期與庫存。</p></div><button type="button" className="yz-btn yz-btn-gho" onClick={load} disabled={loading}><RefreshCw size={16} />重新整理</button></header>{error && <div className="coupon-admin-alert error">{error}</div>}{message && <div className="coupon-admin-alert success">{message}</div>}
    <section className="ui-card coupon-form-card"><div className="coupon-admin-title"><div><h2><Plus size={19} />建立優惠券</h2><p>建立後可切換為上架中，會員才會在點數中心看到。</p></div></div><form className="coupon-form" onSubmit={submit}><label>優惠券代碼<input className="yz-input" required value={form.code} onChange={e => change('code', e.target.value.toUpperCase())} placeholder="例如 SMART50" /></label><label>優惠券名稱<input className="yz-input" required value={form.title} onChange={e => change('title', e.target.value)} placeholder="例如 生鮮折價券" /></label><label className="span-two">簡介<textarea className="yz-input" rows="2" value={form.description} onChange={e => change('description', e.target.value)} /></label><label>兌換點數<input className="yz-input" type="number" min="1" required value={form.points_cost} onChange={e => change('points_cost', e.target.value)} /></label><label>折扣類型<select className="yz-input" value={form.discount_type} onChange={e => change('discount_type', e.target.value)}><option value="fixed">固定折抵</option><option value="percent">百分比折扣</option></select></label><label>折扣數值<input className="yz-input" type="number" min="0.01" step="0.01" max={form.discount_type === 'percent' ? 100 : undefined} required value={form.discount_value} onChange={e => change('discount_value', e.target.value)} /></label><label>庫存（空白不限）<input className="yz-input" type="number" min="1" value={form.stock} onChange={e => change('stock', e.target.value)} /></label><label>開始時間<input className="yz-input" type="datetime-local" value={form.starts_at} onChange={e => change('starts_at', e.target.value)} /></label><label>結束時間<input className="yz-input" type="datetime-local" value={form.expires_at} onChange={e => change('expires_at', e.target.value)} /></label><label>初始狀態<select className="yz-input" value={form.status} onChange={e => change('status', e.target.value)}><option value="draft">草稿</option><option value="active">上架中</option><option value="paused">暫停</option></select></label><div className="coupon-form-actions"><button type="submit" className="yz-btn yz-btn-g" disabled={saving}>{saving ? '建立中…' : '建立優惠券'}</button></div></form></section>
    <section className="ui-card coupon-table-card"><div className="coupon-admin-title"><div><h2><TicketPercent size={19} />優惠券清單</h2><p>共 {coupons.length} 張，兌換數量由正式交易紀錄計算。</p></div></div>{loading ? <div className="coupon-admin-empty">正在載入…</div> : coupons.length === 0 ? <EmptyState title="尚未建立優惠券" description="使用上方表單建立第一張點數兌換券。" /> : <div className="coupon-table-wrap"><table className="coupon-table"><thead><tr><th>券碼／名稱</th><th>兌換點數</th><th>折扣</th><th>有效期／庫存</th><th>狀態</th><th>操作</th></tr></thead><tbody>{coupons.map(coupon => <tr key={coupon.id}><td><strong>{coupon.code}</strong><span>{coupon.title}</span></td><td>{coupon.points_cost} 點</td><td>{coupon.discount_type === 'percent' ? `${coupon.discount_value}%` : `${coupon.discount_value} 元`}</td><td>{coupon.expires_at ? new Date(coupon.expires_at).toLocaleDateString('zh-TW') : '無期限'}<small>{coupon.stock == null ? '不限量' : `${coupon.redeemed_count} / ${coupon.stock}`}</small></td><td><span className={`coupon-status status-${coupon.status}`}>{STATUS_LABEL[coupon.status]}</span></td><td>{['active', 'paused'].includes(coupon.status) && <button type="button" className="yz-btn yz-btn-gho yz-btn-sm" onClick={() => toggle(coupon)}>{coupon.status === 'active' ? '暫停' : '啟用'}</button>}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
