import { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import DashboardChartCard from '../../components/dashboard/DashboardChartCard';
import DashboardFilterBar from '../../components/dashboard/DashboardFilterBar';
import DashboardMetricCard from '../../components/dashboard/DashboardMetricCard';
import ResponsiveDataTable from '../../components/dashboard/ResponsiveDataTable';
import Drawer from '../../components/shared/Drawer';
import EmptyState from '../../components/shared/EmptyState';
import { get } from '../../hooks/useApi';
import { getConsumerAdvice } from '../../lib/consumerAdvice';
import '../../styles/dashboard-overview.css';

export default function DashboardPrices() {
  const [data, setData] = useState(null); const [intel, setIntel] = useState(null); const [markets, setMarkets] = useState([]); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const [market, setMarket] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [sort, setSort] = useState({ key: 'product_name', direction: 'asc' });
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); const [products, marketList, marketIntel] = await Promise.allSettled([get('/api/products'), get('/api/markets'), get('/api/market-intel')]); setError(products.status === 'rejected' ? '行情 API 載入失敗' : ''); if (products.status === 'fulfilled') setData(products.value); if (marketList.status === 'fulfilled') setMarkets(marketList.value.markets || []); if (marketIntel.status === 'fulfilled') setIntel(marketIntel.value); setLoading(false); setRefreshing(false); }, []);
  useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => (Array.isArray(data) ? data : []).filter((row) => (!query || `${row.product_name}${row.market_name || ''}`.includes(query)) && (!market || row.market_name === market) && (!status || row.status === status)).sort((a, b) => String(a[sort.key] ?? '').localeCompare(String(b[sort.key] ?? ''), 'zh-Hant', { numeric: true }) * (sort.direction === 'desc' ? -1 : 1)), [data, query, market, status, sort]);
  const counts = (data || []).reduce((result, row) => { const key = row.status || '資料不足'; result[key] = (result[key] || 0) + 1; return result; }, {}); const pageSize = 20; const pageRows = rows.slice((page - 1) * pageSize, page * pageSize); const onSort = (key) => setSort((current) => current.key === key ? { key, direction: current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction: 'asc' });
  const columns = [{ key: 'product_name', label: '品項' }, { key: 'market_name', label: '市場' }, { key: 'today_price', label: '今日價格', render: (row) => row.today_price == null ? '—' : `${row.today_price} 元` }, { key: 'status', label: '狀態' }, { key: 'trans_date', label: '交易日', render: (row) => row.trans_date || row.latest_trade_date || '—' }];
  return <div className="dashboard-overview">
    <header className="dashboard-overview-heading"><div><p className="eyebrow">Price Management · Read only</p><h1>行情管理</h1><p>唯讀監控正式行情資料，不提供人工修改或刪除。</p></div><button className="overview-refresh" onClick={() => load(true)} disabled={refreshing}><RefreshCw size={17} />{refreshing ? '重新整理中…' : '重新整理'}</button></header>
    <DashboardFilterBar query={query} onQueryChange={(value) => { setQuery(value); setPage(1); }} status={status} onStatusChange={(value) => { setStatus(value); setPage(1); }} onClear={() => { setQuery(''); setStatus(''); setMarket(''); setPage(1); }} />
    <label className="dashboard-price-market-filter">市場<select value={market} onChange={(event) => { setMarket(event.target.value); setPage(1); }}><option value="">全部市場</option>{markets.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>
    {loading && !data ? <div className="dashboard-loading">正在載入行情資料…</div> : <><section className="dashboard-metric-grid"><DashboardMetricCard label="可用行情品項" value={data?.length} status={data ? 'ready' : 'error'} source="/api/products" /><DashboardMetricCard label="便宜品項" value={counts.便宜} status={data ? 'ready' : 'error'} source="/api/products" /><DashboardMetricCard label="正常品項" value={counts.正常} status={data ? 'ready' : 'error'} source="/api/products" /><DashboardMetricCard label="偏貴品項" value={counts.偏貴} status={data ? 'ready' : 'error'} source="/api/products" /><DashboardMetricCard label="市場風險" value={intel?.market_stability?.risk_level} status={intel ? 'ready' : 'error'} source="/api/market-intel" /></section><div className="dashboard-two-columns"><DashboardChartCard title="市場健康摘要" source="/api/market-intel" error={!intel ? '市場情報 API 失敗，未以 0 替代。' : null}><div className="intel-summary"><strong>{intel?.market_stability?.risk_level || '資料不足'}</strong><span>風險指數：{intel?.market_stability?.risk_index ?? '—'}</span></div></DashboardChartCard><DashboardChartCard title="狀態分布" source="/api/products" empty={!data?.length}><div className="distribution-bars">{Object.entries(counts).map(([label, count]) => <div key={label}><span>{label}</span><b>{count}</b></div>)}</div></DashboardChartCard></div>{error && <EmptyState title="部分行情資料無法取得" description={error} />}{!error && !rows.length && <EmptyState title="沒有符合的行情" description="請清除篩選條件或重新整理。" />}<ResponsiveDataTable columns={columns} rows={pageRows} rowKey={(row) => `${row.product_name}-${row.market_name}`} sort={sort} onSort={onSort} onRowClick={setSelected} mobileCardRenderer={(row) => <><strong>{row.product_name}</strong><span>{row.market_name || '市場未提供'} · {row.status || '資料不足'}</span><span>{row.today_price == null ? '價格未提供' : `${row.today_price} 元`} · {getConsumerAdvice(row.status).label}</span></>} page={page} pageSize={pageSize} total={rows.length} onPageChange={setPage} /></>}
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} title="行情詳情">{selected && <div className="price-detail-drawer"><h3>{selected.product_name}</h3><p>{selected.market_name || '市場未提供'} · {selected.status || '資料不足'}</p><strong>{selected.today_price == null ? '資料不足' : `${selected.today_price} 元`}</strong><dl><dt>高價</dt><dd>{selected.upper_price ?? '—'}</dd><dt>低價</dt><dd>{selected.lower_price ?? '—'}</dd><dt>近期平均</dt><dd>{selected.recent_average ?? '—'}</dd></dl><a href={`/product/${encodeURIComponent(selected.product_name)}`}>前往公開商品詳情</a></div>}</Drawer>
  </div>;
}
