export const DEMO_SPECIAL_OFFERS = [
  {
    id: 'demo-fruit-basket',
    badge: '限時特賣',
    merchantIcon: '🍊',
    merchantName: '好日子果園',
    title: '當季鮮果分享籃',
    description: '當季水果一次帶回家，適合家庭分享與日常補給。',
    price: 'NT$ 299',
    originalPrice: 'NT$ 399',
    offerNote: '限量 30 籃．售完為止',
    image: '/demo/special-offer-fruit-basket.png',
    websiteUrl: 'https://example.com/fruit-basket',
  },
  {
    id: 'demo-leafy-vegetables',
    badge: '今日好價',
    merchantIcon: '🥬',
    merchantName: '田邊鮮蔬合作社',
    title: '清爽綠葉蔬菜箱',
    description: '每日採收的新鮮葉菜，簡單料理就能上桌。',
    price: 'NT$ 199',
    originalPrice: 'NT$ 280',
    offerNote: '限時供應．每日數量有限',
    image: '/demo/special-offer-leafy-vegetables.png',
    websiteUrl: 'https://example.com/leafy-vegetables',
  },
];
