export const DEMO_SPECIAL_OFFERS = [
  {
    id: 'demo-fruit-basket',
    badge: '限時特賣',
    merchantIcon: '🍊',
    merchantName: '好日子果園',
    title: '當季鮮果分享籃',
    description: '當季水果一次帶回家，適合家庭分享與日常補給。',
    price: 'NT$ 299',
    originalPrice: 'NT$ 399',
    offerNote: '限量 30 籃．售完為止',
    image: '/demo/special-offer-fruit-basket.png',
    websiteUrl: 'https://example.com/fruit-basket',
  },
  {
    id: 'demo-leafy-vegetables',
    badge: '今日好價',
    merchantIcon: '🥬',
    merchantName: '田邊鮮蔬合作社',
    title: '清爽綠葉蔬菜箱',
    description: '每日採收的新鮮葉菜，簡單料理就能上桌。',
    price: 'NT$ 199',
    originalPrice: 'NT$ 280',
    offerNote: '限時供應．每日數量有限',
    image: '/demo/special-offer-leafy-vegetables.png',
    websiteUrl: 'https://example.com/leafy-vegetables',
  },
  {
    id: 'demo-root-vegetable-box',
    badge: '產地直送',
    merchantIcon: '🥕',
    merchantName: '日光根莖農場',
    title: '根莖蔬菜耐放箱',
    description: '紅蘿蔔、白蘿蔔與馬鈴薯搭配，備料煮湯都方便。',
    price: 'NT$ 249',
    originalPrice: 'NT$ 330',
    offerNote: '限量 40 箱．本週出貨',
    image: '/demo/special-offer-leafy-vegetables.png',
    websiteUrl: 'https://example.com/root-vegetable-box',
  },
  {
    id: 'demo-tomato-bundle',
    badge: '即期超低價',
    merchantIcon: '🍅',
    merchantName: '紅日番茄園',
    title: '熟成番茄料理包',
    description: '熟度正好的番茄，適合做醬汁、沙拉與番茄湯。',
    price: 'NT$ 129',
    originalPrice: 'NT$ 220',
    offerNote: '保存期限短．限時出清 25 組',
    image: '/demo/special-offer-fruit-basket.png',
    websiteUrl: 'https://example.com/tomato-bundle',
  },
  {
    id: 'demo-citrus-box',
    badge: '季節好康',
    merchantIcon: '🍊',
    merchantName: '山線柑橘果園',
    title: '小果柑橘家庭箱',
    description: '酸甜多汁的小果規格，帶皮即食或榨汁都合適。',
    price: 'NT$ 239',
    originalPrice: 'NT$ 320',
    offerNote: '限量 35 箱．售完即止',
    image: '/demo/special-offer-fruit-basket.png',
    websiteUrl: 'https://example.com/citrus-box',
  },
  {
    id: 'demo-sweet-potato-pack',
    badge: '今日下單',
    merchantIcon: '🍠',
    merchantName: '暖土台農小舖',
    title: '香甜地瓜分享包',
    description: '蒸、烤、煮都好吃的地瓜，早餐與點心一次準備好。',
    price: 'NT$ 169',
    originalPrice: 'NT$ 240',
    offerNote: '限量 50 包．今日特價',
    image: '/demo/special-offer-leafy-vegetables.png',
    websiteUrl: 'https://example.com/sweet-potato-pack',
  },
  {
    id: 'demo-mushroom-cooking-set',
    badge: '料理組合',
    merchantIcon: '🍄',
    merchantName: '森林鮮菇農場',
    title: '火鍋綜合菇菇組',
    description: '多種鮮菇一次搭配，火鍋、燴飯與快炒都能使用。',
    price: 'NT$ 189',
    originalPrice: 'NT$ 260',
    offerNote: '每日限量 30 組．冷藏配送',
    image: '/demo/special-offer-leafy-vegetables.png',
    websiteUrl: 'https://example.com/mushroom-cooking-set',
  },
  {
    id: 'demo-rice-family-pack',
    badge: '家庭補給',
    merchantIcon: '🍚',
    merchantName: '禾日米作',
    title: '當季白米家庭包',
    description: '米香清爽、口感穩定，適合日常三餐與家庭備糧。',
    price: 'NT$ 399',
    originalPrice: 'NT$ 480',
    offerNote: '限量 20 組．免運優惠',
    image: '/demo/recommendation-sesame-oil.png',
    websiteUrl: 'https://example.com/rice-family-pack',
  },
  {
    id: 'demo-honey-jar',
    badge: '在地好味',
    merchantIcon: '🍯',
    merchantName: '花田蜂采坊',
    title: '百花蜂蜜分享瓶',
    description: '花香溫潤、沖泡飲品或搭配優格都很適合。',
    price: 'NT$ 299',
    originalPrice: 'NT$ 380',
    offerNote: '限量 28 瓶．產地直送',
    image: '/demo/recommendation-sesame-oil.png',
    websiteUrl: 'https://example.com/honey-jar',
  },
  {
    id: 'demo-dried-mushroom-pack',
    badge: '常備食材',
    merchantIcon: '🫛',
    merchantName: '山間乾物舖',
    title: '日曬菇菇乾貨包',
    description: '香菇、木耳與金針菇組合，家中常備煮湯更快速。',
    price: 'NT$ 229',
    originalPrice: 'NT$ 300',
    offerNote: '限量 45 包．常溫寄送',
    image: '/demo/recommendation-mushrooms.png',
    websiteUrl: 'https://example.com/dried-mushroom-pack',
  },
];

export const DEMO_GOOD_RECOMMENDATIONS = [
  {
    id: 'demo-sesame-oil',
    badge: '高 CP 好物',
    merchantIcon: '🫙',
    merchantName: '禾香手作油坊',
    title: '冷壓芝麻香油',
    description: '香氣濃郁、用途百搭，少量就能提升家常菜風味。',
    price: 'NT$ 260',
    originalPrice: '同級約 NT$ 360',
    offerNote: '推薦理由：用量省、料理適用度高',
    image: '/demo/recommendation-sesame-oil.png',
    websiteUrl: 'https://example.com/sesame-oil',
  },
  {
    id: 'demo-mushrooms',
    badge: '好物推薦',
    merchantIcon: '🍄',
    merchantName: '山里菇菇農場',
    title: '鮮採綜合菇菇籃',
    description: '香菇與蠔菇一次搭配，煮湯、快炒都很方便。',
    price: 'NT$ 220',
    originalPrice: '同級約 NT$ 300',
    offerNote: '推薦理由：份量實在、料理變化多',
    image: '/demo/recommendation-mushrooms.png',
    websiteUrl: 'https://example.com/mushrooms',
  },
];
