CREATE TABLE IF NOT EXISTS public.agri_news_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_key TEXT NOT NULL UNIQUE,
    source_name TEXT NOT NULL,
    source_article_id TEXT,
    title TEXT NOT NULL,
    published_date DATE,
    source_url TEXT NOT NULL UNIQUE,
    content_text TEXT,
    content_hash TEXT,
    parse_status TEXT NOT NULL,
    parse_error TEXT,
    first_fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT agri_news_articles_source_name_check
        CHECK (BTRIM(source_name) <> ''),
    CONSTRAINT agri_news_articles_parse_status_check
        CHECK (parse_status IN ('success', 'partial', 'failed')),
    CONSTRAINT agri_news_articles_content_hash_check
        CHECK (content_hash IS NULL OR char_length(content_hash) = 64)
);

CREATE INDEX IF NOT EXISTS idx_agri_news_articles_published_date_desc
    ON public.agri_news_articles (published_date DESC);

CREATE INDEX IF NOT EXISTS idx_agri_news_articles_source_name
    ON public.agri_news_articles (source_name);

CREATE INDEX IF NOT EXISTS idx_agri_news_articles_parse_status
    ON public.agri_news_articles (parse_status);
