-- Create the SmartBuy AI in-app notifications table for the custom members/JWT backend.
-- This migration intentionally uses public.members(id), integer IDs, and direct Postgres access.

BEGIN;

CREATE TABLE IF NOT EXISTS public.notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    recipient_member_id integer NOT NULL,
    actor_member_id integer NOT NULL,
    type text NOT NULL,
    post_id integer NOT NULL,
    comment_id integer,
    is_read boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_recipient_member_id_fkey
        FOREIGN KEY (recipient_member_id) REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT notifications_actor_member_id_fkey
        FOREIGN KEY (actor_member_id) REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT notifications_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE,
    CONSTRAINT notifications_comment_id_fkey
        FOREIGN KEY (comment_id) REFERENCES public.mutual_aid_comments(id) ON DELETE CASCADE,
    CONSTRAINT notifications_type_check
        CHECK (type IN ('mutual_aid_reply', 'mutual_aid_like'))
);

ALTER TABLE public.notifications
    ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS recipient_member_id integer,
    ADD COLUMN IF NOT EXISTS actor_member_id integer,
    ADD COLUMN IF NOT EXISTS type text,
    ADD COLUMN IF NOT EXISTS post_id integer,
    ADD COLUMN IF NOT EXISTS comment_id integer,
    ADD COLUMN IF NOT EXISTS is_read boolean DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

UPDATE public.notifications
SET is_read = FALSE
WHERE is_read IS NULL;

UPDATE public.notifications
SET created_at = now()
WHERE created_at IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.notifications
        WHERE recipient_member_id IS NULL
           OR actor_member_id IS NULL
           OR type IS NULL
           OR post_id IS NULL
           OR is_read IS NULL
           OR created_at IS NULL
    ) THEN
        RAISE EXCEPTION 'notifications has NULL values in required columns; stop schema alignment';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.notifications
        WHERE type NOT IN ('mutual_aid_reply', 'mutual_aid_like')
    ) THEN
        RAISE EXCEPTION 'notifications has values outside allowed notification types; stop schema alignment';
    END IF;
END;
$$;

ALTER TABLE public.notifications
    ALTER COLUMN recipient_member_id SET NOT NULL,
    ALTER COLUMN actor_member_id SET NOT NULL,
    ALTER COLUMN type SET NOT NULL,
    ALTER COLUMN post_id SET NOT NULL,
    ALTER COLUMN is_read SET DEFAULT FALSE,
    ALTER COLUMN is_read SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT now(),
    ALTER COLUMN created_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND contype = 'p') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND conname = 'notifications_recipient_member_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_recipient_member_id_fkey
            FOREIGN KEY (recipient_member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND conname = 'notifications_actor_member_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_actor_member_id_fkey
            FOREIGN KEY (actor_member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND conname = 'notifications_post_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_post_id_fkey
            FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND conname = 'notifications_comment_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_comment_id_fkey
            FOREIGN KEY (comment_id) REFERENCES public.mutual_aid_comments(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.notifications'::regclass AND conname = 'notifications_type_check') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_type_check
            CHECK (type IN ('mutual_aid_reply', 'mutual_aid_like'));
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS notifications_recipient_unread_idx
    ON public.notifications (recipient_member_id, is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_actor_post_type_idx
    ON public.notifications (actor_member_id, post_id, type);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.notifications FROM anon, authenticated;

DO $$
BEGIN
    IF to_regclass('public.notifications_id_seq') IS NOT NULL THEN
        REVOKE ALL ON SEQUENCE public.notifications_id_seq FROM anon, authenticated;
    END IF;
END;
$$;

COMMIT;
