-- Create the SmartBuy AI mutual-aid tables for the existing custom members/JWT backend.
-- This migration intentionally uses public.members(id), member_id, and integer IDs.
-- It does not create profiles, auth.users foreign keys, or like_count sync triggers.

BEGIN;

DO $$
DECLARE
    v_members_id_type TEXT;
    v_count BIGINT;
BEGIN
    SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_members_id_type
    FROM pg_attribute a
    WHERE a.attrelid = 'public.members'::regclass
      AND a.attname = 'id'
      AND NOT a.attisdropped;

    IF v_members_id_type IS DISTINCT FROM 'integer' THEN
        RAISE EXCEPTION 'public.members.id must be integer, got %', v_members_id_type;
    END IF;

    IF to_regclass('public.mutual_aid_posts') IS NOT NULL THEN
        EXECUTE 'SELECT count(*) FROM public.mutual_aid_posts' INTO v_count;
        IF v_count > 0 AND NOT EXISTS (
            SELECT 1
            FROM pg_attribute id_col
            JOIN pg_attribute member_col
              ON member_col.attrelid = id_col.attrelid
             AND member_col.attname = 'member_id'
             AND NOT member_col.attisdropped
            WHERE id_col.attrelid = 'public.mutual_aid_posts'::regclass
              AND id_col.attname = 'id'
              AND NOT id_col.attisdropped
              AND format_type(id_col.atttypid, id_col.atttypmod) = 'integer'
              AND format_type(member_col.atttypid, member_col.atttypmod) = v_members_id_type
        ) THEN
            RAISE EXCEPTION 'public.mutual_aid_posts has data but incompatible id/member_id columns; stop migration';
        END IF;
    END IF;

    IF to_regclass('public.mutual_aid_comments') IS NOT NULL THEN
        EXECUTE 'SELECT count(*) FROM public.mutual_aid_comments' INTO v_count;
        IF v_count > 0 AND NOT EXISTS (
            SELECT 1
            FROM pg_attribute id_col
            JOIN pg_attribute post_col
              ON post_col.attrelid = id_col.attrelid
             AND post_col.attname = 'post_id'
             AND NOT post_col.attisdropped
            JOIN pg_attribute member_col
              ON member_col.attrelid = id_col.attrelid
             AND member_col.attname = 'member_id'
             AND NOT member_col.attisdropped
            WHERE id_col.attrelid = 'public.mutual_aid_comments'::regclass
              AND id_col.attname = 'id'
              AND NOT id_col.attisdropped
              AND format_type(id_col.atttypid, id_col.atttypmod) = 'integer'
              AND format_type(post_col.atttypid, post_col.atttypmod) = 'integer'
              AND format_type(member_col.atttypid, member_col.atttypmod) = v_members_id_type
        ) THEN
            RAISE EXCEPTION 'public.mutual_aid_comments has data but incompatible id/post_id/member_id columns; stop migration';
        END IF;
    END IF;

    IF to_regclass('public.mutual_aid_likes') IS NOT NULL THEN
        EXECUTE 'SELECT count(*) FROM public.mutual_aid_likes' INTO v_count;
        IF v_count > 0 AND NOT EXISTS (
            SELECT 1
            FROM pg_attribute post_col
            JOIN pg_attribute member_col
              ON member_col.attrelid = post_col.attrelid
             AND member_col.attname = 'member_id'
             AND NOT member_col.attisdropped
            WHERE post_col.attrelid = 'public.mutual_aid_likes'::regclass
              AND post_col.attname = 'post_id'
              AND NOT post_col.attisdropped
              AND format_type(post_col.atttypid, post_col.atttypmod) = 'integer'
              AND format_type(member_col.atttypid, member_col.atttypmod) = v_members_id_type
        ) THEN
            RAISE EXCEPTION 'public.mutual_aid_likes has data but incompatible post_id/member_id columns; stop migration';
        END IF;
    END IF;

    IF to_regclass('public.mutual_aid_saved') IS NOT NULL THEN
        EXECUTE 'SELECT count(*) FROM public.mutual_aid_saved' INTO v_count;
        IF v_count > 0 AND NOT EXISTS (
            SELECT 1
            FROM pg_attribute post_col
            JOIN pg_attribute member_col
              ON member_col.attrelid = post_col.attrelid
             AND member_col.attname = 'member_id'
             AND NOT member_col.attisdropped
            WHERE post_col.attrelid = 'public.mutual_aid_saved'::regclass
              AND post_col.attname = 'post_id'
              AND NOT post_col.attisdropped
              AND format_type(post_col.atttypid, post_col.atttypmod) = 'integer'
              AND format_type(member_col.atttypid, member_col.atttypmod) = v_members_id_type
        ) THEN
            RAISE EXCEPTION 'public.mutual_aid_saved has data but incompatible post_id/member_id columns; stop migration';
        END IF;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.mutual_aid_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    member_id integer NOT NULL,
    type text NOT NULL,
    content text NOT NULL,
    farm_name text,
    location_city text,
    location_addr text,
    location_lat double precision,
    location_lng double precision,
    images text[] NOT NULL DEFAULT ARRAY[]::text[],
    status text NOT NULL DEFAULT 'open',
    like_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT mutual_aid_posts_pkey PRIMARY KEY (id),
    CONSTRAINT mutual_aid_posts_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT mutual_aid_posts_type_check
        CHECK (type IN ('滯銷急售', '求助', '資訊分享')),
    CONSTRAINT mutual_aid_posts_content_not_blank
        CHECK (btrim(content) <> ''),
    CONSTRAINT mutual_aid_posts_images_max_check
        CHECK (cardinality(images) <= 5),
    CONSTRAINT mutual_aid_posts_status_check
        CHECK (status IN ('open', 'dealing', 'closed')),
    CONSTRAINT mutual_aid_posts_like_count_nonnegative
        CHECK (like_count >= 0),
    CONSTRAINT mutual_aid_posts_location_lat_check
        CHECK (location_lat IS NULL OR (location_lat >= '-90'::double precision AND location_lat <= '90'::double precision)),
    CONSTRAINT mutual_aid_posts_location_lng_check
        CHECK (location_lng IS NULL OR (location_lng >= '-180'::double precision AND location_lng <= '180'::double precision))
);

ALTER TABLE public.mutual_aid_posts
    ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS member_id integer,
    ADD COLUMN IF NOT EXISTS type text,
    ADD COLUMN IF NOT EXISTS content text,
    ADD COLUMN IF NOT EXISTS farm_name text,
    ADD COLUMN IF NOT EXISTS location_city text,
    ADD COLUMN IF NOT EXISTS location_addr text,
    ADD COLUMN IF NOT EXISTS location_lat double precision,
    ADD COLUMN IF NOT EXISTS location_lng double precision,
    ADD COLUMN IF NOT EXISTS images text[] DEFAULT ARRAY[]::text[],
    ADD COLUMN IF NOT EXISTS status text DEFAULT 'open',
    ADD COLUMN IF NOT EXISTS like_count integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

UPDATE public.mutual_aid_posts SET images = ARRAY[]::text[] WHERE images IS NULL;
UPDATE public.mutual_aid_posts SET status = 'open' WHERE status IS NULL;
UPDATE public.mutual_aid_posts SET like_count = 0 WHERE like_count IS NULL;
UPDATE public.mutual_aid_posts SET created_at = now() WHERE created_at IS NULL;
UPDATE public.mutual_aid_posts SET updated_at = now() WHERE updated_at IS NULL;

CREATE TABLE IF NOT EXISTS public.mutual_aid_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    post_id integer NOT NULL,
    member_id integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT mutual_aid_comments_pkey PRIMARY KEY (id),
    CONSTRAINT mutual_aid_comments_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE,
    CONSTRAINT mutual_aid_comments_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE,
    CONSTRAINT mutual_aid_comments_content_not_blank
        CHECK (btrim(content) <> '')
);

ALTER TABLE public.mutual_aid_comments
    ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS post_id integer,
    ADD COLUMN IF NOT EXISTS member_id integer,
    ADD COLUMN IF NOT EXISTS content text,
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

UPDATE public.mutual_aid_comments SET created_at = now() WHERE created_at IS NULL;

CREATE TABLE IF NOT EXISTS public.mutual_aid_likes (
    post_id integer NOT NULL,
    member_id integer NOT NULL,
    CONSTRAINT mutual_aid_likes_pkey PRIMARY KEY (post_id, member_id),
    CONSTRAINT mutual_aid_likes_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE,
    CONSTRAINT mutual_aid_likes_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE
);

ALTER TABLE public.mutual_aid_likes
    ADD COLUMN IF NOT EXISTS post_id integer,
    ADD COLUMN IF NOT EXISTS member_id integer;

CREATE TABLE IF NOT EXISTS public.mutual_aid_saved (
    post_id integer NOT NULL,
    member_id integer NOT NULL,
    CONSTRAINT mutual_aid_saved_pkey PRIMARY KEY (post_id, member_id),
    CONSTRAINT mutual_aid_saved_post_id_fkey
        FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE,
    CONSTRAINT mutual_aid_saved_member_id_fkey
        FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE
);

ALTER TABLE public.mutual_aid_saved
    ADD COLUMN IF NOT EXISTS post_id integer,
    ADD COLUMN IF NOT EXISTS member_id integer;

DO $$
BEGIN
    ALTER TABLE public.mutual_aid_posts
        ALTER COLUMN member_id SET NOT NULL,
        ALTER COLUMN type SET NOT NULL,
        ALTER COLUMN content SET NOT NULL,
        ALTER COLUMN images SET DEFAULT ARRAY[]::text[],
        ALTER COLUMN images SET NOT NULL,
        ALTER COLUMN status SET DEFAULT 'open',
        ALTER COLUMN status SET NOT NULL,
        ALTER COLUMN like_count SET DEFAULT 0,
        ALTER COLUMN like_count SET NOT NULL,
        ALTER COLUMN created_at SET DEFAULT now(),
        ALTER COLUMN created_at SET NOT NULL,
        ALTER COLUMN updated_at SET DEFAULT now(),
        ALTER COLUMN updated_at SET NOT NULL;

    ALTER TABLE public.mutual_aid_comments
        ALTER COLUMN post_id SET NOT NULL,
        ALTER COLUMN member_id SET NOT NULL,
        ALTER COLUMN content SET NOT NULL,
        ALTER COLUMN created_at SET DEFAULT now(),
        ALTER COLUMN created_at SET NOT NULL;

    ALTER TABLE public.mutual_aid_likes
        ALTER COLUMN post_id SET NOT NULL,
        ALTER COLUMN member_id SET NOT NULL;

    ALTER TABLE public.mutual_aid_saved
        ALTER COLUMN post_id SET NOT NULL,
        ALTER COLUMN member_id SET NOT NULL;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND contype = 'p') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_pkey PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_member_id_fkey') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_member_id_fkey
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_type_check') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_type_check
            CHECK (type IN ('滯銷急售', '求助', '資訊分享'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_content_not_blank') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_content_not_blank
            CHECK (btrim(content) <> '');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_images_max_check') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_images_max_check
            CHECK (cardinality(images) <= 5);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_status_check') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_status_check
            CHECK (status IN ('open', 'dealing', 'closed'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_like_count_nonnegative') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_like_count_nonnegative
            CHECK (like_count >= 0);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_location_lat_check') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_location_lat_check
            CHECK (location_lat IS NULL OR (location_lat >= '-90'::double precision AND location_lat <= '90'::double precision));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_posts'::regclass AND conname = 'mutual_aid_posts_location_lng_check') THEN
        ALTER TABLE public.mutual_aid_posts ADD CONSTRAINT mutual_aid_posts_location_lng_check
            CHECK (location_lng IS NULL OR (location_lng >= '-180'::double precision AND location_lng <= '180'::double precision));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_comments'::regclass AND contype = 'p') THEN
        ALTER TABLE public.mutual_aid_comments ADD CONSTRAINT mutual_aid_comments_pkey PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_comments'::regclass AND conname = 'mutual_aid_comments_post_id_fkey') THEN
        ALTER TABLE public.mutual_aid_comments ADD CONSTRAINT mutual_aid_comments_post_id_fkey
            FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_comments'::regclass AND conname = 'mutual_aid_comments_member_id_fkey') THEN
        ALTER TABLE public.mutual_aid_comments ADD CONSTRAINT mutual_aid_comments_member_id_fkey
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_comments'::regclass AND conname = 'mutual_aid_comments_content_not_blank') THEN
        ALTER TABLE public.mutual_aid_comments ADD CONSTRAINT mutual_aid_comments_content_not_blank
            CHECK (btrim(content) <> '');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_likes'::regclass AND contype = 'p') THEN
        ALTER TABLE public.mutual_aid_likes ADD CONSTRAINT mutual_aid_likes_pkey PRIMARY KEY (post_id, member_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_likes'::regclass AND conname = 'mutual_aid_likes_post_id_fkey') THEN
        ALTER TABLE public.mutual_aid_likes ADD CONSTRAINT mutual_aid_likes_post_id_fkey
            FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_likes'::regclass AND conname = 'mutual_aid_likes_member_id_fkey') THEN
        ALTER TABLE public.mutual_aid_likes ADD CONSTRAINT mutual_aid_likes_member_id_fkey
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_saved'::regclass AND contype = 'p') THEN
        ALTER TABLE public.mutual_aid_saved ADD CONSTRAINT mutual_aid_saved_pkey PRIMARY KEY (post_id, member_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_saved'::regclass AND conname = 'mutual_aid_saved_post_id_fkey') THEN
        ALTER TABLE public.mutual_aid_saved ADD CONSTRAINT mutual_aid_saved_post_id_fkey
            FOREIGN KEY (post_id) REFERENCES public.mutual_aid_posts(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.mutual_aid_saved'::regclass AND conname = 'mutual_aid_saved_member_id_fkey') THEN
        ALTER TABLE public.mutual_aid_saved ADD CONSTRAINT mutual_aid_saved_member_id_fkey
            FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_mutual_aid_posts_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS mutual_aid_posts_set_updated_at ON public.mutual_aid_posts;
CREATE TRIGGER mutual_aid_posts_set_updated_at
    BEFORE UPDATE ON public.mutual_aid_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.set_mutual_aid_posts_updated_at();

CREATE INDEX IF NOT EXISTS mutual_aid_posts_created_at_idx
    ON public.mutual_aid_posts (created_at DESC);

CREATE INDEX IF NOT EXISTS mutual_aid_posts_type_idx
    ON public.mutual_aid_posts (type);

CREATE INDEX IF NOT EXISTS mutual_aid_posts_location_city_idx
    ON public.mutual_aid_posts (location_city);

CREATE INDEX IF NOT EXISTS mutual_aid_posts_like_count_created_at_idx
    ON public.mutual_aid_posts (like_count DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS mutual_aid_comments_post_id_idx
    ON public.mutual_aid_comments (post_id);

CREATE INDEX IF NOT EXISTS mutual_aid_likes_member_id_idx
    ON public.mutual_aid_likes (member_id);

CREATE INDEX IF NOT EXISTS mutual_aid_saved_member_id_idx
    ON public.mutual_aid_saved (member_id);

ALTER TABLE public.mutual_aid_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutual_aid_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutual_aid_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutual_aid_saved ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.mutual_aid_posts FROM anon, authenticated;
REVOKE ALL ON TABLE public.mutual_aid_comments FROM anon, authenticated;
REVOKE ALL ON TABLE public.mutual_aid_likes FROM anon, authenticated;
REVOKE ALL ON TABLE public.mutual_aid_saved FROM anon, authenticated;

DO $$
BEGIN
    IF to_regclass('public.mutual_aid_posts_id_seq') IS NOT NULL THEN
        REVOKE ALL ON SEQUENCE public.mutual_aid_posts_id_seq FROM anon, authenticated;
    END IF;
    IF to_regclass('public.mutual_aid_comments_id_seq') IS NOT NULL THEN
        REVOKE ALL ON SEQUENCE public.mutual_aid_comments_id_seq FROM anon, authenticated;
    END IF;
END;
$$;

COMMIT;
